### ISSUE TITLE
Exporting Edited Character Meshes Not Retaining Changes (Again) v 1.4.1

### ISSUE THREAD

**Issue by BoboLLC** [Grimrukh/soulstruct-blender#32]
### After I saw the patch rollout yesterday, I was pretty hyped, so I nearly immediately got right back into it and noticed that exporting edited equipment files worked, (kinda) but exporting edited character files still do not.

To make sure it wasn't an issue with my already edited mesh, I edited a new character file with an extremely simple edit.

![Screenshot (54)](https://github.com/Grimrukh/soulstruct-blender/assets/108726830/d30bf2c5-6a1b-4a6a-a90c-d996ed6441a3)
![Screenshot (55)](https://github.com/Grimrukh/soulstruct-blender/assets/108726830/9c18496b-a548-411f-9cc4-d64d7e5e4766)

After I removed the sword on the man serpent mesh, I then clicked on the export character button, and reopened the edited chr file in blender to look if the changes were retained.

![Screenshot (56)](https://github.com/Grimrukh/soulstruct-blender/assets/108726830/f697db17-ab65-4f16-8363-fc012fb00a44)

To my immediate dismay they were not retained.

I also tried using the "Export FLVER" button and while it did keep the edits I made to the mesh(??), it also had a new strange blocky effect take place.

![Screenshot (59)](https://github.com/Grimrukh/soulstruct-blender/assets/108726830/eeb8552d-6287-418d-bad9-7c623523cf00)

I unfortunately believe I've hit the limit as to what I can test on and achieve since I don't really know what's going on in your code unless I got an entire instructional lesson on it. If you need me to directly show you my process on discord, then I am once again willing to set up some time for it. This software mod is dank, and I'd love to improve it in any way that I can.

**Thank you for your continued effort and perseverance. :)**

**Comment by Grimrukh** [comment]
I believe your first problem is just because both "Prefer Import from Project" and "Also Export to Game" are disabled in your settings (I can see it's disabled in your screenshots).

That means that when you export the FLVER with the non-browser options, you are exporting it to your project directory only. When you import with the non-browser options, you are importing it from your game directory, even though the file exists in your project now.

Sorry if this isn't more clear in the setup. I recommend enabling one of those, depending on whether you want changes to be exported to your game directory or not.

As for the second bug, this is a known current issue with split (per-loop) vertex normals not being retained, which is active in another tracked bug. So let me know if your export/import issue is fixed and I'll close this issue.

**Comment by Grimrukh** [comment]
(I just realized that maybe you have your project folder set to the same directory as the game folder, in which case this may be a bug after all. Let me know if so. I'm currently making a lot of changes that might have already fixed this anyway for version 1.5 coming soon.)

**Comment by Grimrukh** [comment]
Nevermind, scratch all of the above - this is definitely still a bug, exactly as you've described. Probably something simple and stupid; will be fixed soon.

**Comment by Grimrukh** [comment]
Yes, it was just one missing line. Fixed for next version, for real this time.

**Comment by BoboLLC** [comment]
Ill move my project folder just in case, and fiddle a bit more cause why not. Better safe than sorry. 
Thank you for your haste in these bug fixes.

**Comment by Grimrukh** [comment]
No need I'd say, you were absolutely right about the issue (the new FLVER just wasn't being added into the CHRBND :/)

I've also got a fix coming for the blocky exported meshes.

**Comment by Grimrukh** [comment]
This should be fixed now in 1.5.0.
