### ISSUE TITLE
Rotation issues with Undead Parish

### ISSUE THREAD

**Issue by ControVR** [Grimrukh/soulstruct-blender#33]
This is a very good tool - I've been enjoying fiddling around with some maps, but I keep having this problem with Undead Parish.

![image](https://github.com/Grimrukh/soulstruct-blender/assets/73795347/ddfc6636-237a-48c4-ab1d-512baa18d4c6)
The bridge and the gate below the dragon never want to line up, and I can't really manually put them back in place.
This happens with PTDE too, not just remastered.

Here's what it looks like using DSMapStudio:
![image](https://github.com/Grimrukh/soulstruct-blender/assets/73795347/f05c7fb1-46fa-4f12-a936-da02642fc579)
(Sorry about the gizmos and whatnot, I don't know if you can disable it or not)

Any way I could fix this myself, or request for it to be fixed?

**Comment by Grimrukh** [comment]
Hey, sorry for the delay. I've identified the issue here: the MSB instances of map pieces that use bones (most of which are in Parish or are just plants) do not have bone pose data. You can see that the source model data (in the 'Map Piece Models' collection) are correct though! Will fix for the next version.

**Comment by Grimrukh** [comment]
Officially fixed in v1.5.1.
