### ISSUE TITLE
Exporting MapPiece m5100B0A15 in Sen's Fortress causes it to become corrupted.

### ISSUE THREAD

**Issue by Mrmoneybags1000** [Grimrukh/soulstruct-blender#34]
Strangely, It's only in-game that it looks like this, In DSMapStudio it looks normal. ![20240310160422_1](https://github.com/Grimrukh/soulstruct-blender/assets/155201471/09038036-f4f3-489e-bff6-73dd2b8d3836) 
![Screenshot (44)](https://github.com/Grimrukh/soulstruct-blender/assets/155201471/4d06f551-cb9f-4a5d-988f-71f4a40be278)

**Comment by Grimrukh** [comment]
Can confirm I've replicated this -- looks fine in both Blender and DSMS, but yeah, obviously something is being exported wrong that the game doesn't like. Should have it fixed soon.

**Comment by Grimrukh** [comment]
Fixed in 1.7.1, hopefully with no other issues.

Problem was two-fold. Maximum number of submesh vertices in DS1 is 65535 (16-bit indices). This is now enforced by Soulstruct export.

The reason Soulstruct was exporting too many vertices was because tiny differences in Blender normals/tangents were being treated as different FLVER vertices. There is now a parameter that merges vertices based on vector dot product, which defaults to 0.999 in the GUI (~2.56 degree max for merging).
