### ISSUE TITLE
An error during Install on 1.9.3 

### ISSUE THREAD

**Issue by mifozski** [Grimrukh/soulstruct-blender#49]
I have an error installing 1.9.3 on Blender 4.1.1:

<img width="694" alt="image" src="https://github.com/Grimrukh/soulstruct-blender/assets/3611730/472f2b06-8e4b-46f7-b496-1a4d8cb8e3bf">

**Comment by Skullman-G** [comment]
I got the same issue using Blender version 4.1.1, 4.1.0 and 4.0.2.

**Comment by HmmmYesss** [comment]
got the same error on blender 4.1 and 3.3

**Comment by capt-slowpoke** [comment]
I am getting this as well, the actual error is 
ModuleNotFoundError: no module named 'soulstruct.utilities'

**Comment by Skullman-G** [comment]
Is there maybe something we can do to fix this issue ourselves?

**Comment by Grimrukh** [comment]
This issue might be related to the presence/absence of the `scripts/addons/io_soulstruct_lib_py31*` folder that needs to be next to `scripts/addons/io_soulstruct`. The `py310` version of the folder is needed for Blender 4.0 and earlier, and the `py311` version is needed for Blender 4.1 and later, so maybe double check the version you need is there (both should have been extracted from the latest release zip).

**Soulstruct for Blender 2.0** is coming very soon and will only support Blender 4.1 and later, due to large changes in how Blender handles certain parts of mesh data. This also means that only Python 3.11 versions of the libraries will be needed, and so any versioning issues should disappear. Will leave this open until then though.

**Comment by Grimrukh** [comment]
This should hopefully be less common now in Soulstruct for Blender 2.0.

**Comment by mifozski** [comment]
@Grimrukh double checked the folders again and they looked to be correct. However, this time I scrolled down the error stack trace and the issue is related to `WinDLL`:
<img width="968" alt="image" src="https://github.com/user-attachments/assets/2f3f9391-d907-4602-9938-028a74d959da">

I'm on Mac 14.4.1

**Comment by Grimrukh** [comment]
Ah, right, yeah Soulstruct does not support Mac/Linux at the moment. This would only affect usage of the Oodle DLL though, so I'll leave this open until I can fix it.

**Comment by mifozski** [comment]
Good to know, thanks for the heads up. Probably should've mentioned that I'm on mac in the first post lol.

**Comment by Grimrukh** [comment]
I've made Oodle import optional (Windows-only) so this bug should be gone. Oodle DCX support is currently unavailable for non-Windows platforms but I'm tracking that feature separately.
