### ISSUE TITLE
Error: zero-size array to reduction operation minimum which has no identity

### ISSUE THREAD

**Issue by fromsoftserve** [Grimrukh/soulstruct-blender#9]
I've gotten this error a few times now on a variety of mappieces I'm editing when I try to export them. and this is with trying explort loose flver, export flver in to binder, msb export on or off, etc. It's usually after editing quite a bit of the mappiece. Like removing wooden boards from a door, or something like that. But 99% of the time edits go just fine on mappieces. I got the error today on mappiece m2090B1A10 in undead burg. I was removing some bricks and wooden boards blocking a doorway. 

Probably missing something simple haha. Also I am on the latest release hotfix.

**Comment by Grimrukh** [comment]
Hmm... could you open the Blender console and send me a screenshot of the full error trace?

**Comment by fromsoftserve** [comment]
sure! took a screenshot of it. oddly I just was editing this mappiece again from the start. halfway through the edits, exporting still worked fine. Then I went ahead and finished removing the boards in front of this door. then the export through this error again. Hmm. 
![Screenshot 2023-11-04 115647](https://github.com/Grimrukh/soulstruct-blender/assets/138341320/6df70874-bfb3-4c01-8590-5cd8979b30ea)

**Comment by Grimrukh** [comment]
I suspect that this is due to a material on your mesh no longer having any faces that actually use it (e.g. it has a wood material but all the wood geometry has been deleted).

Next update will handle this more gracefully by skipping unused materials, but in the meantime, try deleting it yourself in the Material Properties tab of the mesh. (If you're in Edit Mode, you can click the Select button below the material slot list and see which faces use it.)

**Comment by fromsoftserve** [comment]
That makes total sense, thank you!
